/**
 * Test Stub Generator
 *
 * Generates BDD-style test stubs for untested acceptance criteria.
 */

import { AcceptanceCriterion, ActiveStory } from './ac-generator';

/**
 * Infer module location from AC and story context
 */
export function inferModule(ac: AcceptanceCriterion, story: ActiveStory): string {
  // Check story context for module hints
  if (story.context?.relatedCode) {
    const files = story.context.relatedCode.map(f => f.path);

    if (files.some(f => f.startsWith('lambda/auth-edge'))) return 'lambda/auth-edge';
    if (files.some(f => f.startsWith('lambda/referral'))) return 'lambda/referral';
    if (files.some(f => f.startsWith('lambda/custom-message'))) return 'lambda/custom-message';
    if (files.some(f => f.startsWith('infrastructure'))) return 'infrastructure';
    if (files.some(f => f.startsWith('src'))) return 'src';
  }

  // Check AC keywords
  const keywords = ac.keywords.join(' ').toLowerCase();

  if (keywords.includes('api') || keywords.includes('endpoint') || keywords.includes('referral')) {
    return 'lambda/referral';
  }
  if (keywords.includes('auth') || keywords.includes('cognito') || keywords.includes('token')) {
    return 'lambda/auth-edge';
  }
  if (keywords.includes('email') || keywords.includes('message') || keywords.includes('notification')) {
    return 'lambda/custom-message';
  }
  if (keywords.includes('infrastructure') || keywords.includes('cdk') || keywords.includes('stack')) {
    return 'infrastructure';
  }

  // Default to src
  return 'src';
}

/**
 * Generate BDD-style test stub
 */
export function generateBDDStub(ac: AcceptanceCriterion, story: ActiveStory): string {
  const module = inferModule(ac, story);
  const testCases = generateTestCases(ac);

  // Determine import based on module
  let importStatement = '';
  if (module.startsWith('lambda/')) {
    importStatement = `import { handler } from '../index';`;
  } else if (module === 'infrastructure') {
    importStatement = `import * as cdk from 'aws-cdk-lib';\nimport { Template } from 'aws-cdk-lib/assertions';`;
  } else {
    importStatement = `// TODO: Import the function/module being tested`;
  }

  return `// Generated by /compliance for ${ac.id}
// Story #${story.issueNumber}: ${story.title}
// Priority: ${ac.priority} | Type: ${ac.type}

${importStatement}

describe('${ac.id}: ${ac.description}', () => {
${testCases.map(tc => generateTestCase(tc, ac)).join('\n\n')}
});
`;
}

interface TestCase {
  name: string;
  arrange: string;
  act: string;
  assert: string;
}

/**
 * Generate test cases based on AC type
 */
function generateTestCases(ac: AcceptanceCriterion): TestCase[] {
  if (ac.type === 'non-functional') {
    return generateNFRTestCases(ac);
  }

  if (ac.type === 'constraint') {
    return generateConstraintTestCases(ac);
  }

  // Functional test cases
  return [
    {
      name: 'should work correctly under normal conditions',
      arrange: '// TODO: Set up test data and mocks',
      act: '// TODO: Call the function/handler',
      assert: '// TODO: Verify expected behavior'
    },
    {
      name: 'should handle edge cases',
      arrange: '// TODO: Set up edge case scenario',
      act: '// TODO: Call the function/handler',
      assert: '// TODO: Verify edge case handling'
    },
    {
      name: 'should handle errors gracefully',
      arrange: '// TODO: Set up error scenario (invalid input, missing data)',
      act: '// TODO: Call the function/handler',
      assert: '// TODO: Verify error handling (error message, status code)'
    }
  ];
}

/**
 * Generate test cases for non-functional requirements
 */
function generateNFRTestCases(ac: AcceptanceCriterion): TestCase[] {
  const description = ac.description.toLowerCase();

  // Performance test
  if (description.includes('response time') || description.includes('latency')) {
    const timeMatch = description.match(/(\d+)\s*(ms|s|seconds?|milliseconds?)/);
    const threshold = timeMatch ? timeMatch[1] : '2000';
    const unit = timeMatch && timeMatch[2].startsWith('s') ? 's' : 'ms';
    const thresholdMs = unit === 's' ? parseInt(threshold) * 1000 : parseInt(threshold);

    return [
      {
        name: `should respond within ${threshold}${unit} under normal load`,
        arrange: '// TODO: Mock request with normal payload',
        act: `// TODO: Measure execution time\n    // const startTime = Date.now();\n    // await handler(event);\n    // const duration = Date.now() - startTime;`,
        assert: `// TODO: Verify responseTime < ${thresholdMs}\n    // expect(duration).toBeLessThan(${thresholdMs});`
      },
      {
        name: `should respond within ${threshold}${unit} under concurrent load`,
        arrange: '// TODO: Create multiple concurrent requests',
        act: `// TODO: Execute requests in parallel and measure time\n    // const promises = Array(100).fill(0).map(() => handler(event));\n    // const startTime = Date.now();\n    // await Promise.all(promises);\n    // const avgDuration = (Date.now() - startTime) / 100;`,
        assert: `// TODO: Verify average responseTime < ${thresholdMs}\n    // expect(avgDuration).toBeLessThan(${thresholdMs});`
      }
    ];
  }

  // Security test
  if (description.includes('authentication') || description.includes('authorization')) {
    return [
      {
        name: 'should require valid authentication',
        arrange: '// TODO: Create request without auth token',
        act: '// TODO: Call handler',
        assert: '// TODO: Verify 401 Unauthorized response'
      },
      {
        name: 'should reject invalid tokens',
        arrange: '// TODO: Create request with invalid/expired token',
        act: '// TODO: Call handler',
        assert: '// TODO: Verify 401 Unauthorized response'
      },
      {
        name: 'should allow access with valid credentials',
        arrange: '// TODO: Create request with valid auth token',
        act: '// TODO: Call handler',
        assert: '// TODO: Verify 200 OK response'
      }
    ];
  }

  // Reliability test
  if (description.includes('availability') || description.includes('error rate')) {
    return [
      {
        name: 'should handle service failures gracefully',
        arrange: '// TODO: Mock external service failure',
        act: '// TODO: Call handler',
        assert: '// TODO: Verify graceful degradation or retry'
      },
      {
        name: 'should recover from transient errors',
        arrange: '// TODO: Mock intermittent failures',
        act: '// TODO: Call handler with retry logic',
        assert: '// TODO: Verify eventual success'
      }
    ];
  }

  // Generic NFR test
  return [
    {
      name: 'should meet non-functional requirement',
      arrange: '// TODO: Set up test scenario',
      act: '// TODO: Execute operation',
      assert: `// TODO: Verify: ${ac.description}`
    }
  ];
}

/**
 * Generate test cases for constraints
 */
function generateConstraintTestCases(ac: AcceptanceCriterion): TestCase[] {
  return [
    {
      name: 'should enforce constraint',
      arrange: '// TODO: Set up scenario that tests the constraint',
      act: '// TODO: Attempt operation',
      assert: `// TODO: Verify constraint: ${ac.description}`
    },
    {
      name: 'should reject violations',
      arrange: '// TODO: Set up scenario that violates constraint',
      act: '// TODO: Attempt operation',
      assert: '// TODO: Verify rejection (error message, status code)'
    }
  ];
}

/**
 * Format a single test case
 */
function generateTestCase(tc: TestCase, ac: AcceptanceCriterion): string {
  return `  it('${tc.name}', async () => {
    // Arrange
    ${tc.arrange}

    // Act
    ${tc.act}

    // Assert
    ${tc.assert}

    expect(true).toBe(true); // FIXME: Replace with actual assertions
  });`;
}

/**
 * Generate test stubs for all untested P0 ACs
 */
export async function generateMissingTests(
  acs: AcceptanceCriterion[],
  story: ActiveStory,
  writeTool: (filePath: string, content: string) => Promise<void>
): Promise<string[]> {
  const stubs: string[] = [];

  for (const ac of acs) {
    if (!ac.tested && ac.priority === 'P0') {
      const module = inferModule(ac, story);
      const testPath = `${module}/__tests__/ac-${ac.id.toLowerCase()}.test.ts`;
      const stubContent = generateBDDStub(ac, story);

      await writeTool(testPath, stubContent);
      stubs.push(testPath);
      console.log(`✓ Generated test stub: ${testPath}`);
    }
  }

  return stubs;
}
